### ISSUE TITLE
struct.error: unpack requires a string argument of length 16

### ISSUE THREAD

**Issue by APIPLM** [ShySec/pingfs#2]
As run `python ping_fuse.py mount_dir/`,  the below error stack.
```
[NOTICE] selecting server
[NOTICE] www.baidu.com: 1001000.00ms
Traceback (most recent call last):
  File "ping_fuse.py", line 226, in <module>
    server = ping.select_server(log)
  File "/home/sql/pingfs-master/ping.py", line 16, in select_server
    try: delay = single_ping(x,max_timeout)
  File "/home/sql/pingfs-master/ping.py", line 195, in single_ping
    delay = receive_ping(my_socket, my_ID, timeout)
  File "/home/sql/pingfs-master/ping.py", line 180, in receive_ping
    type, code, checksum, packetID = struct.unpack("bbHL", icmpHeader)
struct.error: unpack requires a string argument of length 16


```

**Comment by APIPLM** [comment]
duplicated
